"""initial schema: clients, articles, analyses, runs, settings

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-24
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Kept in sync with newspulse.models. The migration is hand-authored (not
# autogenerated) so the enum value lists and CHECK ranges are explicit here.
_CATEGORY_VALUES = (
    "produkt",
    "personalie",
    "krise",
    "regulatorik",
    "finanzen",
    "wettbewerb",
    "sonstiges",
)
_RUN_STATUS_VALUES = ("ok", "partial", "failed")
_DEFAULT_COUNTRY = "DE"
# DB-level DEFAULT for the JSON array columns, mirroring newspulse.models so a raw
# INSERT that omits them can't violate NOT NULL. "[]" is valid, empty JSON.
_EMPTY_JSON_ARRAY = "[]"


def upgrade() -> None:
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "aliases", sa.JSON(), nullable=False, server_default=_EMPTY_JSON_ARRAY
        ),
        sa.Column("industry", sa.String(length=255), nullable=True),
        sa.Column(
            "country",
            sa.String(length=2),
            nullable=False,
            server_default=_DEFAULT_COUNTRY,
        ),
        sa.Column(
            "keywords", sa.JSON(), nullable=False, server_default=_EMPTY_JSON_ARRAY
        ),
        sa.Column(
            "alert_topics", sa.JSON(), nullable=False, server_default=_EMPTY_JSON_ARRAY
        ),
        sa.Column(
            "active", sa.Boolean(), nullable=False, server_default=sa.text("1")
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("title_hash", sa.String(length=64), nullable=False),
        sa.UniqueConstraint("url", name="uq_articles_url"),
    )
    op.create_index("ix_articles_title_hash", "articles", ["title_hash"])

    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(*_CATEGORY_VALUES, name="category", create_constraint=True),
            nullable=False,
        ),
        sa.Column("relevance_score", sa.Integer(), nullable=False),
        sa.Column("importance_score", sa.Integer(), nullable=False),
        sa.Column(
            "is_alert", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], ondelete="CASCADE"
        ),
        sa.UniqueConstraint(
            "article_id", "client_id", name="uq_analyses_article_client"
        ),
        sa.CheckConstraint(
            "relevance_score >= 0 AND relevance_score <= 10",
            name="ck_analyses_relevance_range",
        ),
        sa.CheckConstraint(
            "importance_score >= 0 AND importance_score <= 10",
            name="ck_analyses_importance_range",
        ),
    )
    op.create_index("ix_analyses_client_id", "analyses", ["client_id"])

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(*_RUN_STATUS_VALUES, name="runstatus", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "articles_found", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "errors", sa.JSON(), nullable=False, server_default=_EMPTY_JSON_ARRAY
        ),
    )

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=255), primary_key=True),
        sa.Column("value", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("settings")
    op.drop_table("runs")
    op.drop_index("ix_analyses_client_id", table_name="analyses")
    op.drop_table("analyses")
    op.drop_index("ix_articles_title_hash", table_name="articles")
    op.drop_table("articles")
    op.drop_table("clients")
